# src_path = "/home/guorui/data"
# data_path = src_path + "/Fold/0"
# save_path = src_path + "/Res/Fold/0"
# num_GPU = 1
src_path = "E:\Data\EmojiPrediction"
data_path = src_path + "\Fold_head\/0"#src_path + "\Fold\/0"
save_path = src_path + "\Res\Fold_head\/0"#src_path + "\Res\Fold\/0"
num_GPU = 0

model = "small"
rnn_mode = "BASIC"
vocab_size = 20000
hidden_size = 400
init_scale = 0.1
learning_rate = 1.0
max_grad_norm = 5
num_layers = 2
num_steps = 20#默认为20，之后会变为文件中句子最大长度
max_epoch = 14#4
max_max_epoch = 55#13
keep_prob = 1.0
lr_decay = 1 / 1.15#0.5
batch_size = 20
